# Quiz 9

In [15]:
class student:
    classes = []

student1 = student()
student2 = student()

In [18]:
student2.classes
student1.classes.append("PIC16A")

In [ ]:
student2.classes

# Quiz 10

In [3]:
def fib(n):
    x, y = 0, 1
    for i in range(n):
        x, y = y, x + y
        yield x

In [4]:
for i in fib(10):
    print(i, end = " ")

1 1 2 3 5 8 13 21 34 55 

# Quiz 11

In [3]:
import numpy as np


In [5]:
A = np.array([[9, 8, 4],
           [6, 2, 2], 
           [7, 7, 5], 
           [0, 1, 4]])

In [6]:
A[2, 1]

7

In [7]:
A[3,:]

array([0, 1, 4])

In [8]:
A[:,1]

array([8, 2, 7, 1])

In [9]:
A[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [27]:
a = np.arange(3)

In [18]:
a[a < 2] = 2
a

array([2, 2, 2])

In [20]:
a[0] += 2

a[1] += 1
a

array([2, 2, 2])

In [22]:
a = np.array([2, 2, 2])
a

array([2, 2, 2])

In [24]:
a[a < 2] = np.array([2, 2])
a

array([2, 2, 2])

In [28]:
a = (a + 2) - a
a

array([2, 2, 2])

# HW 3

In [10]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
car.setdefault("model")

'Mustang'

In [11]:
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

# Quiz 11

In [1]:
import numpy as np

In [8]:
A = np.reshape(np.arange(12), (4, 3))

In [9]:
A.shape

(4, 3)

In [11]:
np.nanmean(A, axis = 0)

array([4.5, 5.5, 6.5])

# Quiz 13

In [1]:
if __name__ == "__main__":

    x = 2

def f(y):

    return x + y

In [2]:
f(5)

7

# Quiz 18

In [1]:
import pandas as pd

In [6]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
df = pd.DataFrame(data, columns = ['a', 'b', 'c'])
df.index += 1
df

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [7]:
df['a']

1    1
2    4
3    7
Name: a, dtype: int64

In [8]:
df.loc[1:3]

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [11]:
df[['c', 'b']]

c  b
1  3  2
2  6  5
3  9  8

In [12]:
df.loc[[3, 2]]

a  b  c
3  7  8  9
2  4  5  6

In [13]:
df[0:2]

a  b  c
1  1  2  3
2  4  5  6

In [14]:
df.loc[0:2]

a  b  c
1  1  2  3
2  4  5  6