# Quiz 9

In [15]:
class student:
    classes = []

student1 = student()
student2 = student()

In [18]:
student2.classes
student1.classes.append("PIC16A")

In [ ]:
student2.classes

# Quiz 10

In [3]:
def fib(n):
    x, y = 0, 1
    for i in range(n):
        x, y = y, x + y
        yield x

In [4]:
for i in fib(10):
    print(i, end = " ")

1 1 2 3 5 8 13 21 34 55 

# Quiz 11

In [3]:
import numpy as np


In [5]:
A = np.array([[9, 8, 4],
           [6, 2, 2], 
           [7, 7, 5], 
           [0, 1, 4]])

In [6]:
A[2, 1]

7

In [7]:
A[3,:]

array([0, 1, 4])

In [8]:
A[:,1]

array([8, 2, 7, 1])

In [9]:
A[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [27]:
a = np.arange(3)

In [18]:
a[a < 2] = 2
a

array([2, 2, 2])

In [20]:
a[0] += 2

a[1] += 1
a

array([2, 2, 2])

In [22]:
a = np.array([2, 2, 2])
a

array([2, 2, 2])

In [24]:
a[a < 2] = np.array([2, 2])
a

array([2, 2, 2])

In [28]:
a = (a + 2) - a
a

array([2, 2, 2])

# HW 3

In [10]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
car.setdefault("model")

'Mustang'

In [11]:
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}